### ISSUE TITLE
ascom problem

### ISSUE THREAD

**Issue by djalex1664** [lkcheng89/lxwebcam#1]
hi,

very nice idea. I have tested your system but I have a problem in ascom testing
![ascom rpoblem](https://user-images.githubusercontent.com/106095762/169849972-9004d9c3-8398-4135-8647-d1d5073921ee.png)
Did you know what is the problem?

Best regards
alex

**Comment by lkcheng89** [comment]
Hi! Apologize for such a late response. It seems that some locale setting causes this problem, hopefully the latest version (v0.2) could solve the issue you just mentioned.

**Comment by djalex1664** [comment]
Hi, thank ou for your response. I have buyed a ZWO camera...
